NUMPY Crash Course

In [8]:
import numpy as np

In [10]:
np.__version__

'1.26.4'

In [4]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

Creating Arrays

In [13]:
mylist = [0,1,2,3,4,5]
mylist

[0, 1, 2, 3, 4, 5]

In [15]:
type(mylist)

list

Convrting List to array

In [18]:
arr= np.array(mylist)
arr

array([0, 1, 2, 3, 4, 5])

In [20]:
type(arr)

numpy.ndarray

In [26]:
np.array(15)

array(15)

In [30]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
np.arange(3.0)

array([0., 1., 2.])

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [38]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
np.arange(20,10)

array([], dtype=int32)

In [42]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [44]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [48]:
ar = np.arange(-30,10)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9])

In [50]:
np.arange(10,10)

array([], dtype=int32)

In [52]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [54]:
np.zeros(3)

array([0., 0., 0.])

In [56]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [70]:
np.zeros((2,2),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [74]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [76]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [78]:
np.ones(3)

array([1., 1., 1.])

In [80]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [82]:
np.twos(2)

AttributeError: module 'numpy' has no attribute 'twos'

In [84]:
rand(3,2)

NameError: name 'rand' is not defined

In [86]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [92]:
np.random.rand(5)

array([0.88279589, 0.05865277, 0.62630035, 0.72609946, 0.30605323])

np-- Package
random--Module
rand--function

In [95]:
np.random.rand(2,4)

array([[0.92813345, 0.901898  , 0.3062465 , 0.93401095],
       [0.82584159, 0.52474511, 0.92428603, 0.03320341]])

In [119]:
np.random.randint(2,20)

12

In [123]:
np.random.randint(2,20,5)

array([ 6,  6, 11, 12,  8])